name: C++ Lint

on:
  workflow_dispatch:
  push:
    paths:
      - "C%2B%2B/**"
      - ".github/workflows/cpp.yaml"
  pull_request:
    paths:
      - "C%2B%2B/**"
      - ".github/workflows/cpp.yaml"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install wget clang-tidy libarmadillo-dev r-cran-rcpparmadillo
          wget https://github.com/tnagler/RcppThread/archive/refs/tags/v2.1.2.tar.gz
          sudo tar -xf v2.1.2.tar.gz -C /

      - name: Lint
        working-directory: C++/src/
        run: |
          clang-tidy *.cpp -header-filter="^.*/C++/src/.*" --use-color -- -I/usr/lib/R/site-library/RcppArmadillo/include -I/usr/lib/R/site-library/Rcpp/include -I/usr/share/R/include -I/RcppThread-2.1.2/inst/include